import { LocationCharacter } from "../models/LocationCharacter";

 export const CHARACTER_MOCK_TEST =[
    {
      id: 1,
      name: 'Character 1',
      gender: 'Male',
      status: '',
      species: '',
      type: '',
      origin: {} as LocationCharacter,
      location: {} as LocationCharacter,
      image: '',
      episode: [],
      url: '',
      created: '',
    },
    {
      id: 2,
      name: 'Character 2',
      gender: 'Female',
      status: '',
      species: '',
      type: '',
      origin: {} as LocationCharacter,
      location: {} as LocationCharacter,
      image: '',
      episode: [],
      url: '',
      created: '',
    },
    {
      id: 3,
      name: 'Character 3',
      gender: 'Genderless',
      status: '',
      species: '',
      type: '',
      origin: {} as LocationCharacter,
      location: {} as LocationCharacter,
      image: '',
      episode: [],
      url: '',
      created: '',
    },
    {
      id: 4,
      name: 'Character 4',
      gender: 'Male',
      status: '',
      species: '',
      type: '',
      origin: {} as LocationCharacter,
      location: {} as LocationCharacter,
      image: '',
      episode: [],
      url: '',
      created: '',
    },
  ];